[package]
name = "mermaid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
lalrpop-util = "0.19.8"
logos = "0.12.1"
thiserror = "1.0.37"

[build-dependencies]
lalrpop = "0.19.8"
